### ISSUE TITLE
[Criar perguntas]  Desenvolvimento

### ISSUE THREAD

**Issue by KronosZbr** [Grupo02-Biopark/ambiente-saga#10]
### Descrição da tarefa

> A criação de perguntas é permitida dentro de um formulário.
> 
> após ser selecionada a opção de criar + ou editar formulários, para o layout das perguntas irão ser desenvolvidos os seguintes campos:
> 
> - Nome da pergunta
> - Um select se a pergunta irá ser de anexo de documentos ou se será de selecionar uma opção de alternativas
> - Um X para cancelar a criação de pergunta
> - Botão criar para finalizar a criação dessa pergunta
> 
> Para a seleção de perguntas quando for selecionada a opção de alternativas ela terá as opções:
> 
> - Conforme
> - Não conforme
>- Não se aplica
> Integrar a criação das perguntas juntamente com a edição/criação do formulário para salvar no banco de dados.

### Descrição dos casos de uso

> - A serem desenvolvidos no documento de casos de uso, após isso irão ser referenciados aqui.

### Requisitos atendidos

> RF-09 O site deve conter um checklist com perguntas específicas para os eixos solicitados.

### Regra de negócio

> Validação se todos os campos foram preenchidos corretamente, para a criação da pergunta.
> Caso tenha selecionado o campo de documentação, quando a pergunta for visualizada ter o campo para anexar e também os >campos de seleção.
> Caso seja para selecionar uma opção ter as opções:
> - Conforme
> - Não conforme
>  - Não se aplica

**Comment by heloshartmann** [comment]
![Image](https://github.com/Grupo02-Biopark/ambiente-saga/assets/133721438/714e9f5e-dfdd-4f4e-87e4-4b76c7bfb5a6)
