### ISSUE TITLE
Listas sem limite de caracteres

### ISSUE THREAD

**Issue by Kainak** [Grupo02-Biopark/ambiente-saga#105]
### Descrição do bug no projeto

Nas páginas que tem listagem de Empresas, Funcionários e Formulários, deve ser feito um limite de caracteres com "..." para que o texto não estoure
isso pode ser feito adicionando ao texto o css:
   max-width: 90px; - só um exemplo de tamanho
   white-space: nowrap;
   overflow: hidden;
   text-overflow: ellipsis;

Bem fácil de arrumar, só pra documentar msm

### Checklist

- [x] O bug foi previamente comunicado com o grupo.
- [x] Eu atualizarei as dependências de acordo com as alterações.
- [x] Eu testarei para que as alterações não interfiram nas demais partes do projeto.

**Comment by GusDechotti** [comment]
@guiigos puxando de ultima hora uma melhoria nas paginas

**Comment by GusDechotti** [comment]
![Image](https://github.com/Grupo02-Biopark/ambiente-saga/assets/75210025/51dd4b2a-4263-44a8-abaa-add24d0a9f1e)
