### ISSUE TITLE
[ADM SIDEBAR] Desenvolvimento:

### ISSUE THREAD

**Issue by GusDechotti** [Grupo02-Biopark/ambiente-saga#16]
### Descrição da tarefa

>Nessa tela o usuário poderá visualizar opções extras. Será desenvolvido:
>+ Opção de levar para um novo formulário
>+ Opção de levar um nova empresa
>+ Opção de cadastrar um novo funcionário

### Descrição dos casos de uso

>+ Clicar no botão novo fomulário leva para a página de criar um fomulário
>+ Clicar no botão nova empresa leva para a página de criar uma empresa
>+ Clicar no botão novo funcionário leva para a página de criar um funcionário

### Requisitos atendidos

>+ RF-01
>+ RF-04
>+ RF-05
>+ RNF-05

### Regra de negócio

>+ Clicar no botão novo fomulário deve levar para a página de criar um fomulário
>+ Clicar no botão nova empresa deve levar para a página de criar uma empresa
>+ Clicar no botão novo funcionário deve levar para a página de criar um funcionário

### Observações

> Botões da side bar são desproporcionalmente grandes e devem ser alterados.

**Comment by heloshartmann** [comment]
![Image](https://github.com/Grupo02-Biopark/ambiente-saga/assets/133721438/e61b4836-a00a-42cb-8f2c-8818e222b544)
