### ISSUE TITLE
[CADASTRO FUNCIONÁRIO] Desenvolvimento:

### ISSUE THREAD

**Issue by GusDechotti** [Grupo02-Biopark/ambiente-saga#17]
### Descrição da tarefa

>Nessa tela é onde o Adm vai colocar as informações sobre o usuário que deseja cadastrar. Será desenvolvido:
>* Terá que preencher os campos:
>    * Nome
>    * Sobrenome
>    * CPF
>    * Número de telefone
>    * Email
>    * Cidade
>    * Senha
>    * Confirmar senha
>* Selecionar se o usuário será adm ou não (Validar se será mantida)
>* Criar ou cancelar

### Descrição dos casos de uso

>+ Clicar em um campo deve deixar adicionar informações
>+ Selecionar a checkbox de adm deverá alterar as permições
>+ Clicar em criar deve adicionar o funcionário
>+ Clicar em cancelar deve fechar as alterações

### Requisitos atendidos

>+ RF-01
>+ RF-02
>+ RF-04
>+ RNF-01
>+ RNF-02
>+ RNF-03
>+ RNF-04
>+ RNF-05
>+ RNF-06

### Regra de negócio

>+ Todos os campos devem estar preenchidos
>+ Criar deve salvar e adicionar o acesso
>+ Cancelar não deve adicioanar

### Observações

> Nenhuma

**Comment by heloshartmann** [comment]
![Image](https://github.com/Grupo02-Biopark/ambiente-saga/assets/133721438/6b79f4dc-0dd2-49fb-8947-cac5627002cb)

**Comment by guiigos** [comment]
Previsão de entrega 22/04!
