### ISSUE TITLE
[CRIAR NOVA EMPRESA] Desenvolvimento

### ISSUE THREAD

**Issue by Kainak** [Grupo02-Biopark/ambiente-saga#24]
### Descrição da tarefa

> Tela que possibilitará o preenchimento dos dados para a criação de uma nova empresa na aplicação
> Deve conter os campos:
> 
> - Nome fantasia;
> - Razão Social;
> - CNPJ;
> - Porte: Contendo as opções Pequeno, médio e grande;
> - Atividade:
> - Contendo as opções: Será digitado pelo usuário manualmente.
> - E-mail; 
> - Botão de cancelar;
> - Botão de Salvar;

### Descrição dos casos de uso

> Após preencher todos os dados e clicar em salvar, uma nova empresa será criada.
> Uma vez incluída no banco de dados, o sistema retornará à tela de lista de empresas e a nova empresa adicionada estará visível na lista.

### Requisitos atendidos

> RF-05

### Regra de negócio

> Todos os campos são obrigatórios;
> 
> Clicando o botão de cancelar, pede-se ao usuário se tem certeza, e se positivo, cancela a operação e retorna à tela anterior. Se negativo mantém as alterações se mantendo na tela de cadastro.
> 
> Deve ser criado um modais de sucesso e insucesso;
> 

### Observações

Não será necessário fotos como do modelo do FIGMA.
Deve ser feito Front, Back, integração com o banco e testes unitários

**Comment by heloshartmann** [comment]
![Image](https://github.com/Grupo02-Biopark/ambiente-saga/assets/133721438/e79fe02f-c209-41ee-a010-1cf4188eac88)

**Comment by guiigos** [comment]
Previsão de entrega 22/04!
