### ISSUE TITLE
[EDIÇÃO DE EMPRESAS]  DESENVOLVIMENTO

### ISSUE THREAD

**Issue by Kainak** [Grupo02-Biopark/ambiente-saga#25]
### Descrição da tarefa

> Tela que possibilitará o preenchimento dos dados para a edição de empresa na aplicação. A tela irá mostrar os dados preenchidos previamente e editáveis.
> 
> Deve conter os campos:
> 
> Nome fantasia;
> Razão Social;
> CNPJ;
> Porte: Contendo as opções Pequeno, médio e grande;
> Atividade:
> Contendo as opções: Será digitado pelo usuário manualmente.
> E-mail;
> Botão de cancelar;
> Botão de Salvar;
> Botão de Excluir;

### Descrição dos casos de uso

> Descrição dos casos de uso
> Preenchido os dados e clicando em salvar, deve ser criado uma nova empresa no banco de dados. Após isso o sistema
> voltará na tela lista de empresas e a empresa deve constar na lista.
> O botão excluir excluirá todos os dados da empresa, e as relações com relatórios, respostas, funcionários.

### Requisitos atendidos

> Não há requisitos para essa tarefa

### Regra de negócio

> Os dados devem estar previamente cadastrados
> 
> Clicando no botão de cancelar, o sistema pede ao usuário se tem certeza. Se negativo retorna para a lista de empresas sem salvar nenhuma alteração. Se positivo salva as alterações no banco.
> 
> Se apertar o botão de excluir, o sistema  pede ao usuário se tem certeza. Se negativo fecha o pop-up se mantendo na página. Se positivo exclui todos os dados da empresa, incluindo os relacionamentos de seus processos de preenchimento de formulários, documentos, pontuação, login e senha.
> 

### Observações

> Deve se atentar para não apagar dados que comprometam outras áreas do sistema, sendo assim somente dados diretamente da empresa e relações em tabelas de relacionamento;

> Será feito back, front, integração com o banco de dados e testes unitários

**Comment by KronosZbr** [comment]
### Sugestões úteis

> Atualizar normalmente;

**Comment by KronosZbr** [comment]
> @guiigos, finalizei minha tarefa então puxei essa para a sprint.
