### ISSUE TITLE
[DELETAR UM USUÁRIO] Desenvolvimento:

### ISSUE THREAD

**Issue by GusDechotti** [Grupo02-Biopark/ambiente-saga#26]
### Descrição da tarefa

>+ Abrir a tela de editar um funcionário tem a opção de excluir no final da página. 

### Descrição dos casos de uso

>+ Caso o cliente clique em deletar um popup deve aparecer exibindo uma pergunta "Tem certeza que deseja exluir [nome]?"
>+ Caso clique em sim o sistema deve excluir o cadastro da pessoa do banco e retornar para a página de todos os usuários
>+ Caso clique em não, o popup deve ser fechado.

### Requisitos atendidos

>+ RF-01
>+ RF-02
>+ RNF-01
>+ RNF-02
>+ RNF-03
>+ RNF-04
>+ RNF-05
>+ RNF-06

### Regra de negócio

>+ Ao aceitar a exclusão o sistema deve deletar toda a conexão do usuário no banco e todas as tabelas onde ele tem atribuido

### Observações

>+ Nenhuma

**Comment by KronosZbr** [comment]
### Sugestões úteis

> Remover acesso;
