### ISSUE TITLE
[Atualização Banco de dados]

### ISSUE THREAD

**Issue by Kainak** [Grupo02-Biopark/ambiente-saga#55]
### Descrição de tarefa

Incluir atributo "status" do tipo Boolean nos Models:
- Usuário
- Pergunta
- Formulário
- Empresa.

### Descrição de casos de uso

Esse atributo funcionará com um Flag de "ativo" e "inativo". Quando o usuário não precisar mais utilizar um desses itens, esta flag servirá para fazer um filtro no select.

### Requisitos atendidos

Servirá para que não seja necessário Deletar esses itens do banco de dados, tornando possível a recuperação dos mesmos à qualquer momento, e evitado que no caso do Formulário e pergunta seja necessário trabalhar com versionamento, o que causaria um impacto grande na estrutura do projeto.

### Regras de negócio

Usuários: quando inativo aparecerá identificado na lista de Funcionários porém impedirá que o mesmo entre no sistema.

Formulário: Quando inativa aparecerá identificada na lista de formulários base, mas não aparecerá na lista para utilizar na avaliação. Não impactará nos formulários concluídos.

Empresas: quando inativa aparecerá na lista identificada como inativa. Não aparecerá na lista na hora de criar uma avaliação. 

Pergunta: Quando ativa parecerá identificada no formulário base e avaliações em andamento, se criada, mas não impactará nos formulários já concluídos e não influenciará na nota do certificados.  

Deve ser criados filtros para aparecerem na lista somente quando desejado.

### Observação

Solicitação do Prof. Willian

**Comment by Kainak** [comment]
@guiigos Boa noite! Conversamos com o professor Willian ontem e ele nos disse que deve ser feito dessa maneira, por isso a criação dessa Issue.

**Comment by GusDechotti** [comment]
Objetivo: alterar o script sql e as classes da aplicação
Modelo lógico do novo banco de dados:


![Image](https://github.com/Grupo02-Biopark/ambiente-saga/assets/75210025/ed75e7c1-cd36-41e8-b211-0680784a267b)

**Comment by GusDechotti** [comment]
Link do novo banco sql:
https://drive.google.com/file/d/1oc_KV2355V4gpGWRDMTKMT_PsRMKLaRA/view?usp=drive_link

**Comment by GusDechotti** [comment]
Novo banco oficial agora:
https://drive.google.com/file/d/1mLuo2cnBIFYxNRkaL76IwOHRrdK17pqT/view?usp=drive_link
