### ISSUE TITLE
[VISUALIZAÇÃO DE FORMULÁRIOS(BASE)] Desenvolvimento

### ISSUE THREAD

**Issue by KronosZbr** [Grupo02-Biopark/ambiente-saga#6]
### Descrição da tarefa

> para a criação de um formulário base irão ser desenvolvidos os seguintes campos com design presente no figma:
> 
> - Pesquisa
> - criar +
> - Exibir os formulários existentes
> 

### Descrição dos casos de uso

> - A serem desenvolvidos no documento de casos de uso, após isso irão ser referenciados aqui.

### Requisitos atendidos

> - N/A

### Regra de negócio

> A exibição de formulários deve mostrar os formulários existentes, por tabela e ter uma opção de edição dos mesmos e cópia, como mostra o design do figma.
> 
> Para a opção de cópia, irá duplicar o formulário com as mesmas perguntas.
> 

### Observações

> A documentação parece estar incompleta, pois não inclui os requisitos de referência necessários.

**Comment by KronosZbr** [comment]
![Image](https://github.com/Grupo02-SAGA/ambiente-saga/assets/106770829/0d56e9d0-4aa6-49cc-ba3d-d9020715e12d)

**Comment by GusDechotti** [comment]
![Image](https://github.com/Grupo02-Biopark/ambiente-saga/assets/75210025/9a01a610-eece-434c-9a58-b3de4ae2f8c9)
