### ISSUE TITLE
Retirar tabelas N-N.

### ISSUE THREAD

**Issue by heloshartmann** [Grupo02-Biopark/ambiente-saga#75]
### Descrição de tarefa

Apagar models (tabelas N-N), alterar script no drive.

### Descrição de casos de uso

N/A

### Requisitos atendidos

N/A

### Regras de negócio

N/A

### Observação

N/A

**Comment by GusDechotti** [comment]
@heloshartmann deve ser alterado o atributo base em formulários para estado sendo um tiny int
