### ISSUE TITLE
[INSERIR SIDEBAR NAS TELAS DE LISTA] - DESENVOLVIMENTO

### ISSUE THREAD

**Issue by KronosZbr** [Grupo02-Biopark/ambiente-saga#85]
### alteração de regra de negócio

>Foi definido na ultima reunião que todas as telas de lista vão ter acesso a sidebar.

>Hoje com a regra de negócio atual temos somente a sidebar no home.

### Descrição de casos de uso

>N/A

### Requisitos atendidos

>N/A

### Regras de negócio

>N/A

### Observação

>Fazer a implementação da sidebar via TH:Fragments em todas as telas que contêm listas.

**Comment by KronosZbr** [comment]
> @devPisa verificar na reunião hoje, sobre o que é essa tarefa;

**Comment by devPisa** [comment]
Issue vai ser executada junto com a issue #98
