### ISSUE TITLE
FIX: AJUSTE BOTÃO ATIVO/INATIVO

### ISSUE THREAD

**Issue by KronosZbr** [Grupo02-Biopark/ambiente-saga#91]
### Descrição do bug no projeto

>Ajustar o botão de ativo/inativo para quando criar um novo formulário vir como ativo

### Quando necessário screenshot do erro.

>N/A

### Observação

>N/A

### Checklist

- [x] O bug foi previamente comunicado com o grupo.
- [x] Eu atualizarei as dependências de acordo com as alterações.
- [x] Eu testarei para que as alterações não interfiram nas demais partes do projeto.

**Comment by KronosZbr** [comment]
@GusDechotti

**Comment by GusDechotti** [comment]
Passado na frente para resolver o bug antes da pre banca

**Comment by GusDechotti** [comment]
Erro comentado na issue fala que o que aconteceria era um erro ao criar um formulário.
Porem durante a validação foi percebido que todos os formulários apresentavam um erro de inverter ativo e inativo 
Alteração foi feita na camada de front
